### ISSUE TITLE
Support for Office 2010

### ISSUE THREAD

**Issue by Rusenche** [DarkDinosaurEx/OfficeRTool#3]
Support for Office 2010

I'm using Windows 7 x64 and Office 2010. This version of the Office suite is simple, clean and my favorite.

Could you consider supporting your tool for Office 2010?

**Comment by DarkDinosaurEx** [comment]
you can use this
https://github.com/DarkDinosaurEx/MS-Office-And-Windows-VL-Deploy-Tools
